name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.1.0
      with:
        REQUIRED_LABELS_ANY: "breaking,bug,enhancement,documentation"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['breaking','bug','enhancement','documentation']"
        BANNED_LABELS: "duplicate"
